name: Build Next.js web application and deploy
on: workflow_dispatch
jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install NPM dependencies
      run: npm install
    - name: Build project assets
      run: npm run build
      
  web-deploy:
  - name: Deploy with FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.jasonthompson.org
        username: u755684214.uploadToBeta
        password: ${{ secrets.ftp_password }}
