name: Build Next.js web application and deploy
on:
  push:
    branches:
      - develop
jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: jongwooo/next-cache@v1
    - name: Install NPM dependencies
      run: npm install
    - name: Build project assets
      run: npm run build
    - name: Cache out directory
      uses: actions/cache@v4
      with:
        id: cache
        path: out/
        key: ${{ runner.os }}-${{ github.run_id }}-outDir
  web-deploy:
    name: Deploy
    needs: build-project
    runs-on: ubuntu-latest
    steps:
    - name: Cache out directory
      uses: actions/cache@v4
      with:
        path: out/
        key: ${{ runner.os }}-${{ github.run_id }}-outDir
    - name: Push files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME_BETA }}
        password: ${{ secrets.FTP_PASSWORD_BETA }}
        dangerous-clean-slate: true
        local-dir: out/
